services:
  nginx:
    container_name: container-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "81:80"
    networks:
      - php-nginx
    volumes:
      - ./:/var/www/html
    depends_on:
      - php

  php:
    container_name: container-php
    build:
      context: .
      dockerfile: php.Dockerfile
    ports:
      - "9000:9000"
    networks:
      - php-nginx
      - mysql-php
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  mysql:
    container_name: container-mysql
    image: mysql:latest
    command: --innodb-force-recovery=4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=coda
      - MYSQL_USER=coda
      - MYSQL_PASSWORD=coda
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      # - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - mysql-php

  phpmyadmin:
    container_name: container-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mysql
    ports:
      - "8080:80"
    networks:
      - mysql-php
    depends_on:
      - mysql

volumes:
  mysql-data:

networks:
  php-nginx:
  mysql-php:
